Login option added
NJACKWinterOfCode/IITP-Connect pull request #7
Opened 2018-12-05 12:23 UTC by Nish-19

Fixes #5 
New login option added in menu drawer

2018-12-09 04:27 UTC, dr0pdb requested changes
Sorry for the late review. Please revert the unnecessary changes.

Also provide a screenshot of how it looks in the app.

2018-12-09 04:27 UTC, dr0pdb commented on app/build.gradle
> +    buildToolsVersion '28.0.3'
please revert this change.

2018-12-09 04:27 UTC, dr0pdb commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:3.2.1'
please revert this change.

2018-12-09 18:48 UTC, srv-twry commented
@Nish-19 Please provide a screenshot of how it looks.

2018-12-10 14:01 UTC, Nish-19 commented
![image](https://user-images.githubusercontent.com/41947720/49736695-d1da7a00-fcb0-11e8-9f9a-c8d73101156d.png)

- In spite of updating the login and logout option in the xml file,the app shows login text for both the login and logout options as shown in the screenshot.


- However in the android studio it displays it correctly as you can find in the screenshot below.
![image](https://user-images.githubusercontent.com/41947720/49737127-069b0100-fcb2-11e8-92b2-f1d89e4619ff.png)

2018-12-10 19:19 UTC, srv-twry commented
@Nish-19 If it is showing Login for both, then there must be an issue with the program right? we have to fix it. I can't merge the PR before that.

2018-12-11 07:22 UTC, Nish-19 commented
@srv-twry Can you give me an idea as to how do I go about this problem? Changing the xml file doesn't seem to be enough. I think I'll have to make a few other changes in other files. I hope you can provide me information on how to go about this.

2019-01-10 11:00 UTC, closed without merging